import { StyleSheet } from "react-native";
import { scaledValue } from "../../utils/design.utils";

export const styles = StyleSheet.create({
  itemsCardView: {
    width: scaledValue(659),
    borderRadius: scaledValue(10),
    paddingRight: scaledValue(10),
    borderWidth: 1,
    borderColor: "#ECECEC",
    shadowColor: "#000",
    elevation: 0.4,
    marginBottom: scaledValue(27),
    flexDirection: "row",
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "space-between",
  },
  activeItemsCardView: {
    paddingTop: scaledValue(19),
    paddingLeft: scaledValue(21),
    paddingBottom: scaledValue(21),
    paddingRight: scaledValue(10),
    width: scaledValue(659),
    height: scaledValue(225),
    borderRadius: scaledValue(10),
    borderWidth: 1,
    borderColor: "#ECECEC",
    shadowColor: "#000",
    elevation: 0.4,
    marginBottom: scaledValue(27),
    flexDirection: "row",
    backgroundColor: "#fff",
    justifyContent: "space-between",
  },
  itemImage: {
    width: scaledValue(95),
    height: scaledValue(95),
    borderRadius: scaledValue(10),
  },
  activeItemImage: {
    width: scaledValue(130),
    height: scaledValue(130),
    borderRadius: scaledValue(10),
    borderWidth: scaledValue(1.5),
    borderColor: "#ECECEC",
  },
  itemText: {
    marginLeft: scaledValue(17),
    fontFamily: "Lato-Medium",
    fontSize: scaledValue(24),
    color: "gray",
    width: scaledValue(350),
  },
  activeItemText: {
    marginLeft: scaledValue(17),
    fontFamily: "Lato-Medium",
    fontSize: scaledValue(24),
    color: "#000",
    marginTop: scaledValue(11),
    width: scaledValue(250),
  },
  stockItemsTextView: {
    flexDirection: "row",
    alignItems: "center",
    height: "100%",
  },
  activeStockItemsTextView: {
    flexDirection: "row",
    alignItems: "center",
    height: scaledValue(58),
  },
  itemImageAndText: {
    flexDirection: "row",
    alignItems: "center",
  },
  activeItemImageAndText: {
    flexDirection: "row",
  },
  stockText: {
    fontSize: scaledValue(20),
    color: "#4C4C4C",
    marginRight: scaledValue(12),
  },
  activeStockText: {
    fontSize: scaledValue(20),
    color: "#000",
    marginRight: scaledValue(12),
  },
  rsTextView: {
    position: "absolute",
    flexDirection: "row",
    alignItems: "center",
    width: scaledValue(468),
    left: scaledValue(168),
    top: scaledValue(89),
    justifyContent: "space-between",
  },
  rsText: {
    fontSize: scaledValue(24),
    fontFamily: "Lato-Regular",
    color: "#F99732",
  },
  discountedMrp: {
    color: "#7D7D7D",
    fontSize: scaledValue(24),
    fontFamily: "Lato-Regular",
  },
  rsMrp: {
    color: "#7D7D7D",
    fontSize: scaledValue(24),
    fontFamily: "Lato-Regular",
    textDecorationLine: "line-through",
  },
  quantityTextView: {
    width: scaledValue(618),
    position: "absolute",
    left: scaledValue(22),
    bottom: scaledValue(21),
    flexDirection: "row",
    justifyContent: "space-between",
  },
  quantityText: {
    fontFamily: "Lato-Regular",
    fontSize: scaledValue(20),
    color: "gray",
  },
  dividerStyle: {
    width: scaledValue(618),
    left: scaledValue(22),
    position: "absolute",
    bottom: scaledValue(58.15),
  },
});
