import { StyleSheet } from "react-native";
import { scaledValue } from "../../utils/design.utils";

export const styles = StyleSheet.create({
  customerOrderHeaderView: {
    width: scaledValue(675),
    flexDirection: "row",
    backgroundColor: "#F89A3A",
    borderTopLeftRadius: scaledValue(8),
    borderTopRightRadius: scaledValue(8),
    alignItems: "center",
    height: scaledValue(83),
    paddingLeft: scaledValue(32),
  },
  itemText: {
    color: "#fff",
    fontSize: scaledValue(21),
    fontFamily: "Lato-Regular",
  },
  orderedPriceText: {
    color: "#fff",
    fontSize: scaledValue(21),
    fontFamily: "Lato-Regular",
    width: scaledValue(80),
    marginLeft: scaledValue(90),
    marginTop: scaledValue(15),
    marginBottom: scaledValue(15),
  },
  priceText: {
    color: "#fff",
    fontSize: scaledValue(21),
    fontFamily: "Lato-Regular",
    width: scaledValue(80),
    marginLeft: scaledValue(110),
    marginBottom: scaledValue(15),
    marginTop: scaledValue(18),
  },
  deliveredItmPrice: {
    marginTop: scaledValue(18),
    width: scaledValue(80),
    marginLeft: scaledValue(110),
    lineHeight: scaledValue(25),
    color: "#fff",
    fontSize: scaledValue(21),
    fontFamily: "Lato-Regular",
    marginBottom: scaledValue(15),
  },

  availabilityText: {
    color: "#fff",
    fontSize: scaledValue(21),
    fontFamily: "Lato-Regular",
    width: scaledValue(108),
    marginLeft: scaledValue(30),
  },
  orderedQuantityText: {
    marginTop: scaledValue(18),
    color: "#fff",
    fontSize: scaledValue(21),
    fontFamily: "Lato-Regular",
    width: scaledValue(110),
    marginLeft: scaledValue(20),
    marginBottom: scaledValue(15),
  },
  deliveredQuantityText: {
    color: "#fff",
    marginTop: scaledValue(18),
    fontSize: scaledValue(21),
    fontFamily: "Lato-Regular",
    width: scaledValue(110),
    marginLeft: scaledValue(20),
    marginBottom: scaledValue(15),
  },
  quantityText: {
    color: "#fff",
    fontSize: scaledValue(21),
    fontFamily: "Lato-Regular",
    width: scaledValue(95),
    marginLeft: scaledValue(31),
  },
  orderedTotalText: {
    color: "#fff",
    fontSize: scaledValue(21),
    fontFamily: "Lato-Regular",
    width: scaledValue(48),
    marginLeft: scaledValue(56),
  },
  totalText: {
    color: "#fff",
    marginTop: scaledValue(30),
    fontSize: scaledValue(21),
    fontFamily: "Lato-Regular",
    width: scaledValue(48),
    marginLeft: scaledValue(36),
    marginBottom: scaledValue(15),
  },
});
